import type { BrittlenessResult, LocatorSpec } from "./types";

const HASH_LIKE_CLASS = /(?:^|-|_)[a-f0-9]{5,}$/i;
const CSS_IN_JS_CLASS = /^(css|sc|jss|emotion|styled)-[a-z0-9]{4,}$/i;

function robust(): BrittlenessResult {
  return { level: "robust", reasons: [] };
}

function medium(reasons: string[]): BrittlenessResult {
  return { level: "medium", reasons };
}

function fragile(reasons: string[]): BrittlenessResult {
  return { level: "fragile", reasons };
}

function looksAutoGenerated(token: string): boolean {
  return HASH_LIKE_CLASS.test(token) || CSS_IN_JS_CLASS.test(token);
}

function assessCssSelector(selector: string): BrittlenessResult {
  const reasons: string[] = [];

  if (/:nth-(child|of-type)\(/i.test(selector)) {
    reasons.push("relies on element position (nth-child/nth-of-type), breaks if sibling order changes");
  }

  const classTokens = selector.match(/\.([\w-]+)/g)?.map((c) => c.slice(1)) ?? [];
  if (classTokens.some(looksAutoGenerated)) {
    reasons.push("uses an auto-generated / build-hashed class name, likely to change between builds");
  }

  const idMatch = selector.match(/#([\w-]+)/);
  if (idMatch && looksAutoGenerated(idMatch[1] ?? "")) {
    reasons.push("uses an id that looks auto-generated");
  }

  if (reasons.length > 0) return fragile(reasons);
  if (idMatch) return robust();
  return medium(["plain CSS selector — more likely to break on markup changes than a role/testid locator"]);
}

function assessXPath(expression: string): BrittlenessResult {
  const reasons: string[] = [];
  if (/\[\d+\]/.test(expression)) {
    reasons.push("relies on positional indexing, breaks if sibling order changes");
  }
  if (/^(\/\/|\/)(html|body)\b/i.test(expression) || expression.split("/").length > 5) {
    reasons.push("long structural path, tightly coupled to current DOM layout");
  }
  if (reasons.length > 0) return fragile(reasons);
  return medium(["XPath fallback — prefer a role or testid locator when one is available"]);
}

export function assessBrittleness(spec: LocatorSpec): BrittlenessResult {
  switch (spec.strategy) {
    case "role":
      return spec.name ? robust() : medium(["role has no accessible name to disambiguate it"]);
    case "testId":
      return robust();
    case "label":
      return robust();
    case "placeholder":
      return medium(["placeholders are often localized or reworded by copy changes"]);
    case "text":
      return medium(["visible text is often localized or reworded by copy changes"]);
    case "css":
      return assessCssSelector(spec.selector);
    case "xpath":
      return assessXPath(spec.expression);
  }
}
