import { getAccessibleName, getImplicitRole } from "./accessibility";
import { assessBrittleness } from "./brittleness";
import { toCSharp, toTypeScript } from "./codegen";
import { cssEscape } from "./cssEscape";
import { matchLocator } from "./matcher";
import type { EngineOptions, LocatorCandidate, LocatorSpec } from "./types";

const FORM_CONTROL_TAGS = new Set(["input", "textarea", "select"]);
const CONTENT_TAGS = new Set([
  "a",
  "button",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "label",
  "li",
  "option",
  "span",
  "p",
  "summary",
]);

const MAX_CANDIDATES = 3;
const MAX_TEXT_LENGTH = 80;

function ownText(el: Element): string {
  return (el.textContent || "").replace(/\s+/g, " ").trim();
}

function isAutoGeneratedToken(token: string): boolean {
  return /(?:^|-|_)[a-f0-9]{5,}$/i.test(token) || /^(css|sc|jss|emotion|styled)-[a-z0-9]{4,}$/i.test(token);
}

function findAssociatedLabelText(el: Element, doc: Document): string | null {
  const id = el.getAttribute("id");
  if (id) {
    const root = el.getRootNode() as Document | ShadowRoot;
    const label = root.querySelector(`label[for="${cssEscape(id)}"]`);
    if (label) {
      const text = ownText(label);
      if (text) return text;
    }
  }
  const wrapping = el.closest("label");
  if (wrapping) {
    const text = ownText(wrapping);
    if (text) return text;
  }
  return null;
}

/** Builds a short-as-possible CSS selector, preferring a plain id, falling back to a tag+nth-of-type path. */
function buildCssSelector(el: Element, doc: Document): string {
  if (el.id) {
    const idSelector = `#${cssEscape(el.id)}`;
    if (doc.querySelectorAll(idSelector).length === 1) return idSelector;
  }

  const segments: string[] = [];
  let node: Element | null = el;

  while (node && node.nodeType === 1) {
    if (node.id) {
      segments.unshift(`#${cssEscape(node.id)}`);
      break;
    }

    let segment = node.tagName.toLowerCase();
    const stableClasses = Array.from(node.classList).filter((c) => !isAutoGeneratedToken(c));
    if (stableClasses.length > 0) {
      segment += stableClasses.map((c) => `.${cssEscape(c)}`).join("");
    }

    const parent: Element | null = node.parentElement;
    if (parent) {
      const sameTagSiblings = Array.from(parent.children).filter(
        (c) => c.tagName === node!.tagName,
      );
      if (sameTagSiblings.length > 1) {
        segment += `:nth-of-type(${sameTagSiblings.indexOf(node) + 1})`;
      }
    }

    segments.unshift(segment);
    node = parent;
  }

  // Try the shortest trailing slice of the path that still uniquely resolves.
  for (let start = segments.length - 1; start >= 0; start--) {
    const candidate = segments.slice(start).join(" > ");
    try {
      if (doc.querySelectorAll(candidate).length === 1) return candidate;
    } catch {
      // ignore malformed intermediate selector
    }
  }

  return segments.join(" > ");
}

function buildXPath(el: Element): string {
  const segments: string[] = [];
  let node: Element | null = el;

  while (node && node.nodeType === 1) {
    const tag = node.tagName.toLowerCase();
    const parent: Element | null = node.parentElement;
    if (!parent) {
      segments.unshift(tag);
      break;
    }
    const sameTagSiblings = Array.from(parent.children).filter((c) => c.tagName === node!.tagName);
    const index = sameTagSiblings.indexOf(node) + 1;
    segments.unshift(sameTagSiblings.length > 1 ? `${tag}[${index}]` : tag);
    node = parent;
  }

  return `//${segments.join("/")}`;
}

function buildSpecs(el: Element, doc: Document, options: EngineOptions): LocatorSpec[] {
  const specs: LocatorSpec[] = [];
  const role = getImplicitRole(el);

  if (role) {
    const name = getAccessibleName(el, doc);
    if (name) {
      specs.push({ strategy: "role", role, name, exact: false });
    } else {
      specs.push({ strategy: "role", role, exact: false });
    }
  }

  if (FORM_CONTROL_TAGS.has(el.tagName.toLowerCase())) {
    const labelText = findAssociatedLabelText(el, doc);
    if (labelText) specs.push({ strategy: "label", text: labelText, exact: false });

    const placeholder = el.getAttribute("placeholder");
    if (placeholder?.trim()) {
      specs.push({ strategy: "placeholder", text: placeholder.trim(), exact: false });
    }
  }

  if (CONTENT_TAGS.has(el.tagName.toLowerCase())) {
    const text = ownText(el);
    if (text && text.length <= MAX_TEXT_LENGTH) {
      specs.push({ strategy: "text", text, exact: false });
    }
  }

  const testIdValue = el.getAttribute(options.testIdAttribute);
  if (testIdValue) {
    specs.push({ strategy: "testId", attribute: options.testIdAttribute, value: testIdValue });
  }

  specs.push({ strategy: "css", selector: buildCssSelector(el, doc) });
  specs.push({ strategy: "xpath", expression: buildXPath(el) });

  return specs;
}

function specKey(spec: LocatorSpec): string {
  return JSON.stringify(spec);
}

export function generateCandidates(
  el: Element,
  options: EngineOptions,
  doc: Document = el.ownerDocument,
): LocatorCandidate[] {
  const specs = buildSpecs(el, doc, options);
  const seen = new Set<string>();
  const candidates: LocatorCandidate[] = [];

  for (const spec of specs) {
    const key = specKey(spec);
    if (seen.has(key)) continue;
    seen.add(key);

    const matches = matchLocator(doc, spec);
    candidates.push({
      spec,
      matchCount: matches.length,
      isUnique: matches.length === 1,
      brittleness: assessBrittleness(spec),
      csharp: toCSharp(spec),
      typescript: toTypeScript(spec),
    });

    if (candidates.length >= MAX_CANDIDATES) break;
  }

  return candidates;
}
