import { getAccessibleName, getImplicitRole, isCssVisible, isExposedToAccessibilityTree } from "./accessibility";
import { assessBrittleness } from "./brittleness";
import { toCSharp, toTypeScript } from "./codegen";
import { cssEscape } from "./cssEscape";
import { matchLocator } from "./matcher";
import type { EngineOptions, LocatorCandidate, LocatorSpec, ResolutionKind } from "./types";

const FORM_CONTROL_TAGS = new Set(["input", "textarea", "select"]);
const CONTENT_TAGS = new Set([
  "a",
  "button",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "label",
  "li",
  "option",
  "span",
  "p",
  "summary",
]);

const MAX_CANDIDATES = 3;
const MAX_TEXT_LENGTH = 80;

function ownText(el: Element): string {
  return (el.textContent || "").replace(/\s+/g, " ").trim();
}

function isAutoGeneratedToken(token: string): boolean {
  return /(?:^|-|_)[a-f0-9]{5,}$/i.test(token) || /^(css|sc|jss|emotion|styled)-[a-z0-9]{4,}$/i.test(token);
}

const STATE_CLASS_PREFIX_RE = /^(is|has|was|will)-/i;
const FRAMEWORK_MARKER_RE = /^(hydrated|ng-|v-|data-v-)/i;
const STATE_WORDS = new Set([
  "active", "selected", "checked", "disabled", "open", "closed", "expanded",
  "collapsed", "hidden", "visible", "current", "focused", "hover", "hovered",
  "pressed", "invalid", "valid", "dirty", "pristine", "touched", "untouched",
  "loading", "error", "success", "highlighted",
]);

/**
 * True for a class that encodes transient state (`sdps-card--selected`, `is-open`)
 * or a framework/hydration marker (`hydrated`, `ng-star-inserted`) rather than a
 * stable structural/styling hook — docs/LOCATOR_STRATEGY.md §2.7. These flip or
 * vanish at runtime with no markup change at all (e.g. a card's `--selected`
 * modifier disappears the moment it's deselected), so a CSS selector built from one
 * can go stale without the page changing.
 */
function isTransientClassToken(token: string): boolean {
  if (FRAMEWORK_MARKER_RE.test(token)) return true;
  if (STATE_CLASS_PREFIX_RE.test(token)) return true;
  const lower = token.toLowerCase();
  if (STATE_WORDS.has(lower)) return true;
  const bemModifier = /--([a-z0-9]+)$/.exec(lower);
  return bemModifier !== null && STATE_WORDS.has(bemModifier[1]!);
}

function findAssociatedLabelText(el: Element, doc: Document): string | null {
  const id = el.getAttribute("id");
  if (id) {
    const root = el.getRootNode() as Document | ShadowRoot;
    const label = root.querySelector(`label[for="${cssEscape(id)}"]`);
    if (label) {
      const text = ownText(label);
      if (text) return text;
    }
  }
  const wrapping = el.closest("label");
  if (wrapping) {
    const text = ownText(wrapping);
    if (text) return text;
  }
  return null;
}

/** Builds a short-as-possible CSS selector, preferring a plain id, falling back to a tag+nth-of-type path. */
function buildCssSelector(el: Element, doc: Document): string {
  if (el.id) {
    const idSelector = `#${cssEscape(el.id)}`;
    if (doc.querySelectorAll(idSelector).length === 1) return idSelector;
  }

  const segments: string[] = [];
  let node: Element | null = el;

  while (node && node.nodeType === 1) {
    if (node.id) {
      segments.unshift(`#${cssEscape(node.id)}`);
      break;
    }

    let segment = node.tagName.toLowerCase();
    const stableClasses = Array.from(node.classList).filter(
      (c) => !isAutoGeneratedToken(c) && !isTransientClassToken(c),
    );
    if (stableClasses.length > 0) {
      segment += stableClasses.map((c) => `.${cssEscape(c)}`).join("");
    }

    const parent: Element | null = node.parentElement;
    if (parent) {
      const sameTagSiblings = Array.from(parent.children).filter(
        (c) => c.tagName === node!.tagName,
      );
      if (sameTagSiblings.length > 1) {
        segment += `:nth-of-type(${sameTagSiblings.indexOf(node) + 1})`;
      }
    }

    segments.unshift(segment);
    node = parent;
  }

  // Try the shortest trailing slice of the path that still uniquely resolves.
  for (let start = segments.length - 1; start >= 0; start--) {
    const candidate = segments.slice(start).join(" > ");
    try {
      if (doc.querySelectorAll(candidate).length === 1) return candidate;
    } catch {
      // ignore malformed intermediate selector
    }
  }

  return segments.join(" > ");
}

function buildXPath(el: Element): string {
  const segments: string[] = [];
  let node: Element | null = el;

  while (node && node.nodeType === 1) {
    const tag = node.tagName.toLowerCase();
    const parent: Element | null = node.parentElement;
    if (!parent) {
      segments.unshift(tag);
      break;
    }
    const sameTagSiblings = Array.from(parent.children).filter((c) => c.tagName === node!.tagName);
    const index = sameTagSiblings.indexOf(node) + 1;
    segments.unshift(sameTagSiblings.length > 1 ? `${tag}[${index}]` : tag);
    node = parent;
  }

  return `//${segments.join("/")}`;
}

/**
 * Strategy order here follows docs/LOCATOR_STRATEGY.md §2: role → label →
 * placeholder → text → testId → css → xpath. That doc is the source of truth for
 * *why* — keep it in sync with any change here, including the still-unimplemented
 * pieces it tracks (altText/title strategies, and resolving to a nearby interactive
 * ancestor/descendant when `el` itself has no role — see §1).
 */
function buildSpecs(el: Element, doc: Document, options: EngineOptions): LocatorSpec[] {
  const specs: LocatorSpec[] = [];
  const role = getImplicitRole(el);

  if (role) {
    const name = getAccessibleName(el, doc);
    if (name) {
      specs.push({ strategy: "role", role, name, exact: false });
    } else {
      specs.push({ strategy: "role", role, exact: false });
    }
  }

  if (FORM_CONTROL_TAGS.has(el.tagName.toLowerCase())) {
    const labelText = findAssociatedLabelText(el, doc);
    if (labelText) specs.push({ strategy: "label", text: labelText, exact: false });

    const placeholder = el.getAttribute("placeholder");
    if (placeholder?.trim()) {
      specs.push({ strategy: "placeholder", text: placeholder.trim(), exact: false });
    }
  }

  if (CONTENT_TAGS.has(el.tagName.toLowerCase())) {
    const text = ownText(el);
    if (text && text.length <= MAX_TEXT_LENGTH) {
      specs.push({ strategy: "text", text, exact: false });
    }
  }

  const testIdValue = el.getAttribute(options.testIdAttribute);
  if (testIdValue) {
    specs.push({ strategy: "testId", attribute: options.testIdAttribute, value: testIdValue });
  }

  specs.push({ strategy: "css", selector: buildCssSelector(el, doc) });
  specs.push({ strategy: "xpath", expression: buildXPath(el) });

  return specs;
}

const MAX_RESOLUTION_DEPTH = 3;

// Roles worth resolving *to* — actionable controls, not structural/landmark roles
// (heading, img, list, navigation, ...) that happen to have a computable name but
// aren't a better locator target than the element the user actually picked.
const INTERACTIVE_ROLES = new Set([
  "button",
  "link",
  "checkbox",
  "radio",
  "switch",
  "textbox",
  "combobox",
  "listbox",
  "option",
  "menuitem",
  "menuitemcheckbox",
  "menuitemradio",
  "tab",
  "slider",
  "spinbutton",
  "searchbox",
]);

function isInteractiveResolutionTarget(el: Element, doc: Document): boolean {
  const role = getImplicitRole(el);
  if (!role || !INTERACTIVE_ROLES.has(role)) return false;
  if (!isExposedToAccessibilityTree(el)) return false;
  return getAccessibleName(el, doc).length > 0;
}

function hasDirectSpec(specs: LocatorSpec[]): boolean {
  return specs.some((spec) => spec.strategy !== "css" && spec.strategy !== "xpath");
}

function findInteractiveAncestor(el: Element, doc: Document): Element | null {
  let node: Element | null = el.parentElement;
  let depth = 0;
  while (node && depth < MAX_RESOLUTION_DEPTH) {
    if (isInteractiveResolutionTarget(node, doc)) return node;
    node = node.parentElement;
    depth += 1;
  }
  return null;
}

function collectInteractiveDescendants(el: Element, doc: Document): Element[] {
  const found: Element[] = [];
  const walk = (node: Element, depth: number): void => {
    if (depth > MAX_RESOLUTION_DEPTH) return;
    for (const child of Array.from(node.children)) {
      if (isInteractiveResolutionTarget(child, doc)) found.push(child);
      else walk(child, depth + 1);
    }
  };
  walk(el, 0);
  return found;
}

interface ResolvedTarget {
  element: Element;
  resolvedVia: ResolutionKind | null;
}

/**
 * Implements docs/LOCATOR_STRATEGY.md §1: when `el` itself yields no role/label/
 * placeholder/text/testId spec of its own — common for custom-element wrappers
 * around a real control, e.g. a `<sdps-card>` wrapping a labelled radio `<input>` —
 * look for a uniquely-identifiable interactive ancestor, then descendant, to build
 * specs from instead. Promotes only on an unambiguous single match; zero or
 * multiple candidates always fall back to `el` itself, even if that means a worse
 * (css/xpath-only) locator — a silently wrong guess is worse than an honestly
 * fragile one.
 */
function resolveTargetElement(el: Element, doc: Document, directSpecs: LocatorSpec[]): ResolvedTarget {
  if (hasDirectSpec(directSpecs)) return { element: el, resolvedVia: null };

  const ancestor = findInteractiveAncestor(el, doc);
  if (ancestor) return { element: ancestor, resolvedVia: "ancestor" };

  const descendants = collectInteractiveDescendants(el, doc);
  if (descendants.length === 1) return { element: descendants[0]!, resolvedVia: "descendant" };

  return { element: el, resolvedVia: null };
}

function specKey(spec: LocatorSpec): string {
  return JSON.stringify(spec);
}

/** Builds a fresh candidate from a spec — the single place match-derived fields are computed, so a live re-check or an exact-toggle can recompute a candidate without duplicating this logic (and risking it drifting out of sync, as happened with the hasHiddenMatch check). */
function buildCandidate(spec: LocatorSpec, doc: Document): LocatorCandidate {
  const matches = matchLocator(doc, spec);
  return {
    spec,
    matchCount: matches.length,
    isUnique: matches.length === 1,
    // CSS-hidden only (display:none/visibility:hidden) — this is what makes an
    // element non-actionable for Playwright regardless of locator strategy.
    // aria-hidden alone does NOT belong here: it's a common, intentional
    // pattern on visible decorative icons, and only affects accessibility-tree
    // based strategies (role/label), which already filter it out themselves.
    hasHiddenMatch: matches.some((match) => !isCssVisible(match)),
    brittleness: assessBrittleness(spec),
    csharp: toCSharp(spec),
    typescript: toTypeScript(spec),
  };
}

function buildCandidateList(specs: LocatorSpec[], doc: Document): LocatorCandidate[] {
  const seen = new Set<string>();
  const candidates: LocatorCandidate[] = [];

  for (const spec of specs) {
    const key = specKey(spec);
    if (seen.has(key)) continue;
    seen.add(key);

    candidates.push(buildCandidate(spec, doc));

    if (candidates.length >= MAX_CANDIDATES) break;
  }

  return candidates;
}

export interface PickResult {
  candidates: LocatorCandidate[];
  /** The element candidates were actually built from — `el` unless resolution (docs/LOCATOR_STRATEGY.md §1) promoted to an ancestor/descendant. */
  target: Element;
  resolvedVia: ResolutionKind | null;
}

/**
 * Resolves the best target element (docs/LOCATOR_STRATEGY.md §1) and generates its
 * ranked candidates. Prefer this over `generateCandidates` wherever the caller can
 * act on `target`/`resolvedVia` — e.g. to highlight the element candidates actually
 * target and tell the user when it differs from the one they picked.
 */
export function pickCandidates(
  el: Element,
  options: EngineOptions,
  doc: Document = el.ownerDocument,
): PickResult {
  const directSpecs = buildSpecs(el, doc, options);
  const { element: target, resolvedVia } = resolveTargetElement(el, doc, directSpecs);
  const specs = resolvedVia ? buildSpecs(target, doc, options) : directSpecs;
  return { candidates: buildCandidateList(specs, doc), target, resolvedVia };
}

export function generateCandidates(
  el: Element,
  options: EngineOptions,
  doc: Document = el.ownerDocument,
): LocatorCandidate[] {
  return pickCandidates(el, options, doc).candidates;
}

/** Recomputes matchCount/isUnique/hasHiddenMatch (and codegen/brittleness, which are cheap) for a set of previously-generated candidates against the current DOM state — used to keep the panel from going stale on an SPA that re-renders after a pick. */
export function refreshCandidates(candidates: LocatorCandidate[], doc: Document): LocatorCandidate[] {
  return candidates.map((candidate) => buildCandidate(candidate.spec, doc));
}

/** Flips the `exact` flag on the candidate at `index` (a no-op if that strategy has no `exact` field) and recomputes it against the current DOM. */
export function withExact(
  candidates: LocatorCandidate[],
  index: number,
  exact: boolean,
  doc: Document,
): LocatorCandidate[] {
  const target = candidates[index];
  if (!target || !("exact" in target.spec)) return candidates;
  const nextSpec = { ...target.spec, exact } as LocatorSpec;
  const next = candidates.slice();
  next[index] = buildCandidate(nextSpec, doc);
  return next;
}
